version: '3.4'

services:
  ejemploapirest.webapi:
    image: ${DOCKER_REGISTRY-}ejemploapirestwebapi
    build:
      context: .
      dockerfile: EjemploApiRest.WebApi/Dockerfile
    ports:
        - "80:80"
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    ports:
        - "27017:27017"